<form action="index.php?route=register" method="POST">
    <fieldset>
        <legend>Inscription</legend>
        
        <div class="field">
            <label for="pseudo">Pseudo</label>
            <div class="pseudo"><input type="text" id="pseudo" name="pseudo"></div>
        </div>
        
        <div class="field">
            <label for="lastname">E-mail</label>
            <div class="email"><input type="text" id="email" name="email"></div>
        </div>
        
        <div class="field">
            <label for="password">Password</label>
            <div class="password"><input type="password" id="password" name="password"></div>
        </div>
        
        <div class="field">
            <label for="c-password">Confirm Password</label>
            <div class="c-password"><input type="password" id="c-password" name="c-password"></div>
        </div>
        
        <div>
            <input type="submit" value="Inscription">
        </div>
        
    </fieldset>
</form>