<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Distorsion</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="index.php?route=login">Connexion</a></li>
                <li><a href="index.php?route=register">Création de compte</a></li>
                <li><a href="index.php?route=index_room">Room</a></li>
                <li><a href="index.php?route=index_category">Categories</a></li>
            </ul>
        </nav>
    </header>
       
    <?php require $this->template ;?>

</body>
</html>