<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Distorsion</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="index.php?route=login">Connexion</a></li>
                <li><a href="index.php?route=register">Création de compte</a></li>
                <li><a href="index.php?route=index_room">Room</a></li>
                <li><a href="index.php?route=index_category">Categories</a></li>
            </ul>
        </nav>
    </header>
       
    <?php 
    switch($this->template){
        case "edit_user":
             require "/home/homes/francisrouxel/sites/php/res04_php_distorsion/views/user/edit_user.phtml";
            break;
        case "login":
             require "/home/homes/francisrouxel/sites/php/res04_php_distorsion/views/login/login.phtml";
            break;
        case "register":
             require "/home/homes/francisrouxel/sites/php/res04_php_distorsion/views/register/register.phtml";
            break;
        case "index_room":
            require "/home/homes/francisrouxel/sites/php/res04_php_distorsion/views/room/index_room.phtml";
            break;
        case "create_room":
            require "/home/homes/francisrouxel/sites/php/res04_php_distorsion/views/room/create_room.phtml";
            break;
        case"edit_room":
            require "/home/homes/francisrouxel/sites/php/res04_php_distorsion/room/edit_room.phtml";
            break;
    }
    ?>

</body>
</html>