<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
        <link rel="stylesheet" href="../../assets/styles/css/style.css" />

</head>
<body>
    <div class="formulaire">
    
<form action="index.php?route=login" method="POST">
    <fieldset>
        <legend>Connexion</legend>
        
        <div class="field">
            <label for="pseudo">Pseudo</label>
            <div class="pseudo"><input type="text" id="pseudo" name="pseudo"></div>
        </div>
        
        <div class="field">
            <label for="password">Password</label>
            <div class="password"><input type="password" id="password" name="password"></div>
        </div>
        <div class="btn">
            
            <div class="button1">
                <input class="button" type="submit" value="Connexion">
            </div>
            
            <div class="button2">

                 <a href="index.php?route=register">Inscription</a>
            </div>
         </div>

    </fieldset>
    </form>

</div>

</body>
</html>