<form  action="index.php?route=create_room"method="POST">
    <fieldset>
        <legend>Create Room</legend>
        
        <div class="field">
            <label for="create-room">Room name : </label>
            <div class="create-room"><input type="text" id="create-room" name="name"></div>
        </div>
        
         <div class="field">
            <label for="desc-room">Description : </label>
            <div class="desc-room"><input type="text" id="desc-room" name="description"></div>
        </div>
        
        <div>
            <input class="btnCreate" type="submit" value="Create">
        </div>
    </fieldset>
</form>